name: Deploy to Azure Container App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Added for manual triggers

env:
  AZURE_CONTAINER_REGISTRY: justscoreacr   # Updated to your registry name
  CONTAINER_APP_NAME: justscorereact
  CONTAINER_APP_RESOURCE_GROUP: justscore-rg
  IMAGE_NAME: justscorereact           # Changed from samples/hello-world to justscorereact
  NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}  # Add this if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}        # Changed from REGISTRY_USERNAME
        password: ${{ secrets.ACR_PASSWORD }}        # Changed from REGISTRY_PASSWORD
    
    - name: Build and push container image
      run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Azure Container App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP }} \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} 